var countDownDate=new Date("Dec 4, 2018 00:00:00").getTime();var x=setInterval(function(){var now=new Date().getTime();var distance=countDownDate- now;var days=Math.floor(distance/(1000*60*60*24));var hours=Math.floor((distance%(1000*60*60*24))/ (1000 * 60 * 60));
var minutes=Math.floor((distance%(1000*60*60))/ (1000 * 60));
var seconds=Math.floor((distance%(1000*60))/ 1000);
document.getElementById("Seconds").innerHTML=seconds;document.getElementById("Days").innerHTML=days;document.getElementById("Minutes").innerHTML=minutes;document.getElementById("Hours").innerHTML=hours;if(distance<0){clearInterval(x);document.getElementById("demo").innerHTML="Started";}},1000);(function($){"use strict";function toggleMobileNavigation(){var navbar=$("#navbar");var navLinks=$("#navbar > ul > li > a:not(.dropdown-toggle)");var openBtn=$(".navbar-header .open-btn");var closeBtn=$("#navbar .close-navbar");openBtn.on("click",function(){if(!navbar.hasClass("slideInn")){navbar.addClass("slideInn");}
return false;})
closeBtn.on("click",function(){if(navbar.hasClass("slideInn")){navbar.removeClass("slideInn");}
return false;})
navLinks.on("click",function(){if(navbar.hasClass("slideInn")){navbar.removeClass("slideInn");}
return false;})}
toggleMobileNavigation();function bgParallax(){if($(".parallax").length){$(".parallax").each(function(){var height=$(this).position().top;var resize=height- $(window).scrollTop();var doParallax=-(resize/5);var positionValue=doParallax+"px";var img=$(this).data("bg-image");$(this).css({backgroundImage:"url("+ img+")",backgroundPosition:"50%"+ positionValue,backgroundSize:"cover"});});}}
bgParallax();function sliderBgSetting(){if($(".hero-slider .slide").length){$(".hero-slider .slide").each(function(){var $this=$(this);var img=$this.children(img);var imgSrc=img.attr("src");$this.css({backgroundImage:"url("+ imgSrc+")",backgroundSize:"cover",backgroundPosition:"center center"})});}}
if($(".modal").length){$('.modal').appendTo("body");}
function preloader(){if($('.preloader').length){$('.preloader').delay(100).fadeOut(500,function(){wow.init();if($(".hero-slider").length){$(".hero-slider").owlCarousel({items:1,autoplay:true,loop:true,animateOut:'fadeOut'});$('.hero .owl-controls').appendTo(".hero-slider-wrapper").addClass("hero-controls");}});}}
var sections=$("section"),nav=$("#navbar"),nav_height=nav.outerHeight();function activeMenuItem(){var cur_pos=$(window).scrollTop()+ 2;sections.each(function(){var top=$(this).offset().top- nav_height,bottom=top+ $(this).outerHeight();if(cur_pos>=top&&cur_pos<=bottom){nav.find("ul > li > a").parent().removeClass("active");nav.find("a[href='#"+ $(this).attr('id')+"']").parent().addClass("active");}else if(cur_pos===2){nav.find("ul > li > a").parent().removeClass("active");}});}
$(function(){$("#navbar > ul > li > a:not(.dropdown-toggle)").on("click",function(){if(location.pathname.replace(/^\//,'')===this.pathname.replace(/^\//,'')&&location.hostname===this.hostname){var target=$(this.hash);target=target.length?target:$("[name="+ this.hash.slice(1)+"]");if(target.length){$("html, body").animate({scrollTop:target.offset().top- 40},1000,"easeInOutExpo");return false;}}
return false;});});$(window).on("scroll",function(){var header=$("#header");var headerHeight=$("#header").innerHeight();var scroll=$(window).scrollTop();var top=1;if(scroll>top){header.addClass("sticky");$("body").css({'padding-top':headerHeight+'px'})}else{header.removeClass("sticky");$("body").css({'padding-top':0})}});var wow=new WOW({boxClass:'wow',animateClass:'animated',offset:0,mobile:true,live:true});if($("#clock").length){var todaysDate=new Date();var marrigeDate=new Date(todaysDate.getFullYear()+ 0,12- 1,31);$("#clock").countdown({until:marrigeDate}).on('update.countdown',function(event){$(this).addClass("asdf");});}
if($(".proposal-slider").length){$(".proposal-slider").owlCarousel({items:2,loop:true,margin:15,dots:false,nav:true,navText:["<i class='fa fa-long-arrow-left'></i>","<i class='fa fa-long-arrow-right'></i>"]});}
if($(".date-slider").length){$(".date-slider").owlCarousel({items:2,loop:true,margin:15,dots:false,nav:true,navText:["<i class='fa fa-long-arrow-left'></i>","<i class='fa fa-long-arrow-right'></i>"]});}
if($(".video").length){$(".video").on("click",function(){$.fancybox({href:this.href,type:$(this).data("type"),'title':this.title,helpers:{title:{type:'inside'},media:{}}});return false});}
if($(".accomodation-slider").length){$(".accomodation-slider").owlCarousel({items:2,loop:true,margin:10,dots:false,nav:true,navText:["<i class='fa fa-long-arrow-left'></i>","<i class='fa fa-long-arrow-right'></i>"]});}
if($(".food-slider").length){$(".food-slider").owlCarousel({items:2,loop:true,margin:10,dots:false,nav:true,navText:["<i class='fa fa-long-arrow-left'></i>","<i class='fa fa-long-arrow-right'></i>"]});}
if($(".gallery .fancybox").length){$(".gallery .fancybox").fancybox({openEffect:"elastic",closeEffect:"elastic",wrapCSS:"project-fancybox-title-style",helpers:{title:{type:'inside'}},beforeShow:function(){$(".fancybox-wrap").addClass("gallery-fancybox");}});}
if($(".gallery .video").length){$(".gallery .video").on("click",function(){$.fancybox({href:this.href,type:$(this).data("type"),'title':this.title,helpers:{title:{type:'inside'},media:{}},beforeShow:function(){$(".fancybox-wrap").addClass("gallery-fancybox");}});return false});}
function galleryFiltering(){if($(".gallery-content").length){var $container=$('.grid-wrapper');$container.isotope({filter:'*',animationOptions:{duration:750,easing:'linear',queue:false,}});$(".gallery-filters li a").on("click",function(e){$('.gallery-filters li a.current').removeClass('current');$(this).addClass('current');var selector=$(this).attr('data-filter');$container.isotope({filter:selector,animationOptions:{duration:750,easing:'linear',queue:false,}});return false;});}}
galleryFiltering();if($(".event-panel").length){var allLinks=$(".event-panel .panel-title > a");allLinks.on("click",function(){var $this=$(this);$this.closest(".panel-heading").toggleClass("current");$this.closest(".panel").siblings().find(".panel-heading").removeClass("current");console.log();});}
function map(){var locations=[['<h4>Main Ceremony</h4> Hotel Radison ',23.818876,90.408078,1],['<h4>Reciption Party</h4> InterContinental Dhaka',23.744214,90.396446,2],];var map=new google.maps.Map(document.getElementById('map'),{center:new google.maps.LatLng(23.815183,90.402966),zoom:11,scrollwheel:false,mapTypeId:google.maps.MapTypeId.ROADMAP});var infowindow=new google.maps.InfoWindow();var marker,i;for(i=0;i<locations.length;i++){marker=new google.maps.Marker({position:new google.maps.LatLng(locations[i][1],locations[i][2]),map:map,icon:'images/map-marker.png'});google.maps.event.addListener(marker,'click',(function(marker,i){return function(){infowindow.setContent(locations[i][0]);infowindow.open(map,marker);}})(marker,i));}};if($("#rsvp-form").length){$("#rsvp-form").validate({rules:{name:{required:true,minlength:2},email:"required",guest:{required:true},events:{required:true}},messages:{name:"Please enter your name",email:"Please enter your email",guest:"Select your number of guest",events:"Select your event list"},submitHandler:function(form){$.ajax({type:"POST",url:"mail.php",data:$(form).serialize(),success:function(){$("#loader").hide();$("#success").slideDown("slow");setTimeout(function(){$("#success").slideUp("slow");},3000);form.reset();},error:function(){$("#loader").hide();$("#error").slideDown("slow");setTimeout(function(){$("#error").slideUp("slow");},3000);}});return false;}});}
$(window).on('load',function(){preloader();bgParallax();sliderBgSetting();galleryFiltering();if($(".map").length){map();}});$(window).on("resize",function(){galleryFiltering();});$(window).on("scroll",function(){activeMenuItem();bgParallax();});})(window.jQuery);